import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight } from "lucide-react";
import { formatMetricVal } from "@/lib/formatters";
import type { PerformanceData } from "./performanceShared";
import { EmptyState } from "./performanceShared";

const templates = ["Moving Average Crossover", "Trend Pullback", "Breakout and Retest", "Session Breakout", "Momentum Continuation", "Custom Rules"];

export function BacktestingWorkspace({ data }: { data: PerformanceData }) {
  const [form, setForm] = useState({ instrument: "EUR/USD", timeframe: "H4", start: "", end: "", entry: "", exit: "", stopLoss: "", takeProfit: "", session: "London", template: templates[0] });
  const request = useMemo(() => `Backtest ${form.template} on ${form.instrument} ${form.timeframe} using historical data${form.start || form.end ? ` from ${form.start || "available start"} to ${form.end || "available end"}` : ""}. Entry rules: ${form.entry || "describe objective entry rules"}. Exit rules: ${form.exit || "describe objective exit rules"}. Stop loss: ${form.stopLoss || "not specified"}. Take profit: ${form.takeProfit || "not specified"}. Session filter: ${form.session}. Report drawdown, win rate, profit factor, validation status and overfitting risks. Historical performance does not guarantee future results.`, [form]);
  const latest = data.reportRuns[0];
  return <section className="rounded-2xl border bg-card p-5" aria-labelledby="backtesting-title"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Demonstration Interface</p><h2 id="backtesting-title" className="text-xl font-semibold">Strategy Backtesting</h2><p className="mt-2 text-sm text-muted-foreground">Historical performance does not guarantee future results.</p></div><Link to="/agent" state={{ preparedAnalysisRequest: request }} className="inline-flex items-center gap-2 rounded-lg bg-primary px-3 py-2 text-sm font-semibold text-primary-foreground hover:opacity-90">Prepare Market Intelligence Request <ArrowRight className="h-4 w-4" /></Link></div><div className="mt-5 grid gap-4 lg:grid-cols-2"><div className="grid gap-3 sm:grid-cols-2"><Field label="Instrument" value={form.instrument} onChange={(v) => setForm({ ...form, instrument: v })} /><Field label="Timeframe" value={form.timeframe} onChange={(v) => setForm({ ...form, timeframe: v })} /><Field label="Historical start date" type="date" value={form.start} onChange={(v) => setForm({ ...form, start: v })} /><Field label="Historical end date" type="date" value={form.end} onChange={(v) => setForm({ ...form, end: v })} /><Field label="Entry rules" value={form.entry} onChange={(v) => setForm({ ...form, entry: v })} /><Field label="Exit rules" value={form.exit} onChange={(v) => setForm({ ...form, exit: v })} /><Field label="Stop loss" value={form.stopLoss} onChange={(v) => setForm({ ...form, stopLoss: v })} /><Field label="Take profit" value={form.takeProfit} onChange={(v) => setForm({ ...form, takeProfit: v })} /><Field label="Session filter" value={form.session} onChange={(v) => setForm({ ...form, session: v })} /><label className="text-sm font-medium">Strategy template<select value={form.template} onChange={(e) => setForm({ ...form, template: e.target.value })} className="mt-2 w-full rounded-lg border bg-background px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary/40">{templates.map((item) => <option key={item}>{item}</option>)}</select></label></div><div>{latest ? <div className="grid gap-3 sm:grid-cols-2"><Metric label="Total trades" value="No verified data available" /><Metric label="Win rate" value="No verified data available" /><Metric label="Profit factor" value="No verified data available" /><Metric label="Maximum drawdown" value="No verified data available" /><Metric label="Average return" value={latest.total_return != null ? formatMetricVal("total_return", latest.total_return) : "No verified data available"} /><Metric label="Average risk-to-reward" value="No verified data available" /><Metric label="Longest losing streak" value="No verified data available" /><Metric label="Validation status" value={latest.status || "unknown"} /></div> : <EmptyState />}</div></div></section>;
}

function Field({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <label className="text-sm font-medium">{label}<input type={type} value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 w-full rounded-lg border bg-background px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary/40" /></label>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border bg-background/70 p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-mono text-sm font-semibold tabular-nums">{value}</p></div>; }
