import { summarizeJournalEntries, groupEntriesByPair, groupEntriesBySession, groupEntriesByWeekday } from "@/lib/journal";
import type { JournalState, PerformanceData } from "./performanceShared";
import { EmptyState } from "./performanceShared";

export function PerformanceBreakdown({ runs, reportRuns, loading, error, entries }: PerformanceData & JournalState) {
  const summary = summarizeJournalEntries(entries);
  const pairGroups = groupEntriesByPair(entries);
  const sessionGroups = groupEntriesBySession(entries);
  const weekdayGroups = groupEntriesByWeekday(entries);
  const data: PerformanceData = { runs, reportRuns, loading, error };
  const wins = reportRuns.filter((run) => Number(run.total_return) > 0).length;
  const losses = reportRuns.filter((run) => Number(run.total_return) < 0).length;
  return <section className="rounded-2xl border bg-card p-5" aria-labelledby="performance-breakdown-title"><h2 id="performance-breakdown-title" className="text-xl font-semibold">Performance Breakdown</h2><p className="mt-2 text-sm text-muted-foreground">Verified run data is used where available. Journal dimensions remain local to this browser session.</p><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3"><Breakdown title="Performance by Pair" groups={pairGroups} empty="No journal pair data in this browser session." /><Breakdown title="Performance by Session" groups={sessionGroups} empty="No journal session data in this browser session." /><Breakdown title="Performance by Weekday" groups={weekdayGroups} empty="No journal weekday data in this browser session." /><article className="rounded-xl border bg-background/70 p-4"><h3 className="font-semibold">Winning vs Losing Runs</h3>{data.reportRuns.length ? <p className="mt-3 font-mono text-sm tabular-nums">Positive verified report returns: {wins}<br />Negative verified report returns: {losses}</p> : <EmptyState />}</article><article className="rounded-xl border bg-background/70 p-4"><h3 className="font-semibold">Drawdown History</h3><EmptyState body="Run-list summaries do not expose drawdown history. Open an analysis report for verified equity and drawdown charts when available." /></article><article className="rounded-xl border bg-background/70 p-4"><h3 className="font-semibold">Validation Outcomes</h3>{data.reportRuns.length ? <p className="mt-3 text-sm text-muted-foreground">Latest verified status: <span className="font-mono text-foreground">{data.reportRuns[0].status || "unknown"}</span></p> : <EmptyState />}</article></div><p className="mt-3 text-xs text-muted-foreground">Local journal summary: {summary.totalEntries} entries, {(summary.winRate * 100).toFixed(1)}% win rate, {summary.averageRisk.toFixed(2)}% average risk.</p></section>;
}
function Breakdown({ title, groups, empty }: { title: string; groups: Record<string, unknown[]>; empty: string }) { const keys = Object.keys(groups); return <article className="rounded-xl border bg-background/70 p-4"><h3 className="font-semibold">{title}</h3>{keys.length ? <ul className="mt-3 space-y-2 text-sm">{keys.map((key) => <li key={key} className="flex justify-between gap-3"><span>{key}</span><span className="font-mono tabular-nums">{groups[key].length}</span></li>)}</ul> : <EmptyState body={empty} />}</article>; }
