import { Link } from "react-router-dom";
import { ArrowRight } from "lucide-react";
import { formatMetricVal } from "@/lib/formatters";
import type { PerformanceData } from "./performanceShared";
import { EmptyState, formatRunDate } from "./performanceShared";

export function RecentAnalysisRuns({ data }: { data: PerformanceData }) {
  const recent = data.runs.slice(0, 8);
  return <section className="rounded-2xl border bg-card p-5" aria-labelledby="recent-runs-title"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 id="recent-runs-title" className="text-xl font-semibold">Recent Analysis Runs</h2><p className="mt-2 text-sm text-muted-foreground">Reuses existing run summaries and report routes.</p></div><Link to="/reports" className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-semibold hover:bg-muted">View All Opportunity Reports <ArrowRight className="h-4 w-4" /></Link></div>{recent.length ? <div className="mt-5 overflow-x-auto rounded-xl border"><table className="w-full min-w-[760px] text-sm"><caption className="sr-only">Recent analysis runs</caption><thead className="bg-muted/50 text-left text-xs uppercase text-muted-foreground"><tr><th className="p-2">Run title</th><th className="p-2">Date</th><th className="p-2">Status</th><th className="p-2">Provider</th><th className="p-2">Model</th><th className="p-2">Validation status</th><th className="p-2">Metrics</th><th className="p-2">Report link</th></tr></thead><tbody>{recent.map((run) => <tr key={run.run_id} className="border-t"><td className="max-w-[220px] truncate p-2">{run.prompt || run.run_id}</td><td className="p-2">{formatRunDate(run.created_at)}</td><td className="p-2">{run.status || "unknown"}</td><td className="p-2">No verified data available</td><td className="p-2">No verified data available</td><td className="p-2">{run.status || "unknown"}</td><td className="p-2 font-mono">{run.total_return != null ? formatMetricVal("total_return", run.total_return) : "—"}{run.sharpe != null ? ` / ${formatMetricVal("sharpe", run.sharpe)}` : ""}</td><td className="p-2"><Link to={`/runs/${run.run_id}`} className="text-primary hover:underline">Analysis Report</Link></td></tr>)}</tbody></table></div> : <div className="mt-5"><EmptyState /></div>}</section>;
}
