import type { ReactNode } from "react";
import { calculateDrawdown, calculateRecoveryTarget, classifyRiskHealth } from "@/lib/calculators";
import { Currency, NumberField, RiskBadge, type RiskInputs } from "./riskShared";

export function DrawdownSimulator({ inputs, setInputs }: { inputs: RiskInputs; setInputs: (next: RiskInputs) => void }) {
  let result = null;
  try {
    result = inputs.accountBalance > 0 && inputs.riskPercentage >= 0 && inputs.consecutiveLosses >= 0 ? calculateDrawdown(inputs.accountBalance, inputs.riskPercentage, Math.trunc(inputs.consecutiveLosses)) : null;
  } catch {
    result = null;
  }
  const amountLost = result ? inputs.accountBalance - result.endingBalance : 0;
  const recovery = result ? calculateRecoveryTarget(inputs.accountBalance, result.endingBalance) : 0;
  return <section className="rounded-2xl border bg-card p-5"><h2 className="text-xl font-semibold">Drawdown Simulator</h2><div className="mt-5 grid gap-4 lg:grid-cols-2"><div className="grid gap-3 sm:grid-cols-2"><NumberField label="Starting balance" value={inputs.accountBalance} min={0.01} onChange={(v) => setInputs({ ...inputs, accountBalance: Math.max(0.01, v) })} /><NumberField label="Risk percentage per trade" value={inputs.riskPercentage} onChange={(v) => setInputs({ ...inputs, riskPercentage: Math.max(0, v) })} /><NumberField label="Consecutive losses" value={inputs.consecutiveLosses} step="1" onChange={(v) => setInputs({ ...inputs, consecutiveLosses: Math.max(0, Math.trunc(v)) })} /><NumberField label="Optional recovery target" value={inputs.recoveryTarget} onChange={(v) => setInputs({ ...inputs, recoveryTarget: Math.max(0, v) })} /></div><div aria-live="polite" className="space-y-3">{result && <><div className="grid gap-3 sm:grid-cols-2"><Output label="Ending balance" value={<Currency value={result.endingBalance} currency={inputs.currency} />} /><Output label="Total amount lost" value={<Currency value={amountLost} currency={inputs.currency} />} /><Output label="Drawdown percentage" value={`${result.drawdownPercentage.toFixed(2)}%`} /><Output label="Recovery percentage required" value={`${recovery.toFixed(2)}%`} /><Output label="Remaining capital" value={<Currency value={result.endingBalance} currency={inputs.currency} />} /><div className="rounded-xl border bg-background/70 p-3"><p className="text-xs text-muted-foreground">Risk classification</p><div className="mt-2"><RiskBadge value={classifyRiskHealth(inputs.riskPercentage)} /></div></div></div><svg role="img" aria-label="Lightweight loss sequence chart" viewBox="0 0 320 80" className="h-24 w-full rounded-xl border bg-background p-2"><polyline fill="none" stroke="hsl(var(--primary))" strokeWidth="3" points={Array.from({ length: Math.max(2, inputs.consecutiveLosses + 1) }, (_, i) => `${(i / Math.max(1, inputs.consecutiveLosses)) * 300 + 10},${20 + (i / Math.max(1, inputs.consecutiveLosses)) * 45}`).join(' ')} /></svg><p className="text-sm text-muted-foreground">A 50% drawdown requires a 100% gain to recover because recovery is calculated from the reduced balance.</p></>}</div></div></section>;
}
function Output({ label, value }: { label: string; value: ReactNode }) { return <div className="rounded-xl border bg-background/70 p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-mono font-semibold tabular-nums">{value}</p></div>; }
