import type { ReactNode } from "react";
import { calculatePositionSize, classifyRiskHealth } from "@/lib/calculators";
import { Currency, NumberField, RiskBadge, type RiskInputs } from "./riskShared";

export function PositionSizeCalculator({ inputs, setInputs }: { inputs: RiskInputs; setInputs: (next: RiskInputs) => void }) {
  const errors = [inputs.accountBalance <= 0 && "Account balance must be greater than 0.", inputs.riskPercentage < 0 && "Risk cannot be negative.", inputs.stopLossPips <= 0 && "Stop-loss distance must be greater than 0.", inputs.pipValuePerStandardLot <= 0 && "Pip value must be greater than 0."].filter(Boolean) as string[];
  const result = errors.length ? null : calculatePositionSize(inputs);
  const classification = classifyRiskHealth(Math.max(0, inputs.riskPercentage));
  const warning = inputs.riskPercentage > 10 ? "Critical exposure" : inputs.riskPercentage > 5 ? "High risk" : inputs.riskPercentage > 2 ? "Elevated caution" : null;
  return <section className="rounded-2xl border bg-card p-5"><h2 className="text-xl font-semibold">Position Size Calculator</h2><p className="mt-2 text-sm text-muted-foreground">Estimated position size based on entered assumptions.</p><div className="mt-5 grid gap-4 lg:grid-cols-2"><div className="grid gap-3 sm:grid-cols-2"><NumberField label="Account balance" value={inputs.accountBalance} min={0.01} onChange={(v) => setInputs({ ...inputs, accountBalance: Math.max(0.01, v) })} error={inputs.accountBalance <= 0 ? "Account balance must be greater than 0." : undefined} /><NumberField label="Risk percentage" value={inputs.riskPercentage} onChange={(v) => setInputs({ ...inputs, riskPercentage: Math.max(0, v) })} error={inputs.riskPercentage < 0 ? "Risk cannot be negative." : undefined} /><NumberField label="Stop-loss distance in pips" value={inputs.stopLossPips} min={0.01} onChange={(v) => setInputs({ ...inputs, stopLossPips: Math.max(0.01, v) })} error={inputs.stopLossPips <= 0 ? "Stop-loss distance must be greater than 0." : undefined} /><NumberField label="Pip value per standard lot" value={inputs.pipValuePerStandardLot} min={0.01} onChange={(v) => setInputs({ ...inputs, pipValuePerStandardLot: Math.max(0.01, v) })} error={inputs.pipValuePerStandardLot <= 0 ? "Pip value must be greater than 0." : undefined} /><label className="text-sm font-medium">Currency display<select value={inputs.currency} onChange={(e) => setInputs({ ...inputs, currency: e.target.value })} className="mt-2 w-full rounded-lg border bg-background px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary/40"><option>USD</option><option>EUR</option><option>GBP</option></select></label></div><div aria-live="polite" className="grid gap-3">{result ? <><Output label="Risk amount" value={<Currency value={result.riskAmount} currency={inputs.currency} />} /><Output label="Estimated standard lots" value={result.standardLots.toFixed(3)} /><Output label="Estimated mini lots" value={result.miniLots.toFixed(2)} /><Output label="Estimated micro lots" value={result.microLots.toFixed(1)} /><Output label="Percentage of account exposed" value={`${inputs.riskPercentage}%`} /><div className="rounded-xl border bg-background/70 p-3"><p className="text-xs text-muted-foreground">Risk classification</p><div className="mt-2"><RiskBadge value={classification} /></div></div></> : errors.map((e) => <p key={e} className="text-sm text-danger">{e}</p>)}{warning && <p className="rounded-xl border border-warning/30 bg-warning/5 p-3 text-sm text-muted-foreground">{warning}: review this exposure against written risk rules.</p>}</div></div></section>;
}
function Output({ label, value }: { label: string; value: ReactNode }) { return <div className="rounded-xl border bg-background/70 p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-mono font-semibold tabular-nums">{value}</p></div>; }
