import { compareRiskScenarios, type RiskScenarioInput } from "@/lib/calculators";
import { Currency, NumberField, RiskBadge, type RiskInputs } from "./riskShared";
import { useState } from "react";

const defaults: RiskScenarioInput[] = [
  { name: "Conservative", accountBalance: 1000, riskPercentage: 0.5, rewardRatio: 1.5, winRate: 55, numberOfTrades: 20 },
  { name: "Balanced", accountBalance: 1000, riskPercentage: 1, rewardRatio: 2, winRate: 50, numberOfTrades: 20 },
  { name: "Aggressive", accountBalance: 1000, riskPercentage: 3, rewardRatio: 2.5, winRate: 45, numberOfTrades: 20 },
];
export function ScenarioComparison({ inputs }: { inputs: RiskInputs }) {
  const [scenarios, setScenarios] = useState(defaults);
  const merged = scenarios.map((s) => ({ ...s, accountBalance: inputs.accountBalance }));
  const results = compareRiskScenarios(merged);
  const update = (index: number, patch: Partial<RiskScenarioInput>) => setScenarios((prev) => prev.map((s, i) => i === index ? { ...s, ...patch } : s));
  return <section className="rounded-2xl border bg-card p-5"><h2 className="text-xl font-semibold">Scenario Comparison</h2><div className="mt-5 grid gap-4 lg:grid-cols-3">{scenarios.map((scenario, i) => <div key={scenario.name} className="rounded-xl border bg-background/60 p-4"><h3 className="font-semibold">{scenario.name}</h3><div className="mt-3 grid gap-2"><NumberField label={`${scenario.name} risk percentage`} value={scenario.riskPercentage} onChange={(v) => update(i, { riskPercentage: Math.max(0, v) })} /><NumberField label={`${scenario.name} reward ratio`} value={scenario.rewardRatio} onChange={(v) => update(i, { rewardRatio: Math.max(0.01, v) })} /><NumberField label={`${scenario.name} win rate`} value={scenario.winRate} onChange={(v) => update(i, { winRate: Math.max(0, Math.min(100, v)) })} /><NumberField label={`${scenario.name} trades`} value={scenario.numberOfTrades} step="1" onChange={(v) => update(i, { numberOfTrades: Math.max(1, Math.trunc(v)) })} /></div></div>)}</div><div className="mt-5 overflow-x-auto"><table className="hidden w-full border-collapse text-sm md:table"><thead><tr className="text-left text-muted-foreground"><th className="border p-2">Scenario</th><th className="border p-2">Estimated ending balance</th><th className="border p-2">Estimated net outcome</th><th className="border p-2">Drawdown warning</th><th className="border p-2">Break-even win rate</th><th className="border p-2">Risk classification</th></tr></thead><tbody>{results.map((r) => <tr key={r.name}><td className="border p-2 font-medium">{r.name}</td><td className="border p-2 font-mono"><Currency value={r.endingBalance} currency={inputs.currency} /></td><td className="border p-2 font-mono"><Currency value={r.netOutcome} currency={inputs.currency} /></td><td className="border p-2">{r.drawdownWarning}</td><td className="border p-2">{(r.breakEvenWinRate * 100).toFixed(2)}%</td><td className="border p-2"><RiskBadge value={r.riskClassification} /></td></tr>)}</tbody></table><div className="grid gap-3 md:hidden">{results.map((r) => <div key={r.name} className="rounded-xl border bg-background/60 p-3"><h3 className="font-semibold">{r.name}</h3><p>Ending balance: <Currency value={r.endingBalance} currency={inputs.currency} /></p><p>Net outcome: <Currency value={r.netOutcome} currency={inputs.currency} /></p><p>{r.drawdownWarning}</p><p>Break-even: {(r.breakEvenWinRate * 100).toFixed(2)}%</p><RiskBadge value={r.riskClassification} /></div>)}</div></div></section>;
}
